services:
  - type: web
    name: photography-assistant
    runtime: python
    pythonVersion: "3.11.8"  # Downgrade for better compatibility
    buildCommand: |
      pip install --upgrade pip
      pip install --no-deps opencv-python-headless==4.9.0.80
      pip install -r backend/requirements.txt
    startCommand: ./backend/start.sh

# Core Flask
flask==2.3.2
gunicorn==20.1.0

# Image Processing (Lightweight)
pillow==10.1.0
numpy==1.26.4

# API Support
flask-cors==4.0.0
python-dotenv==1.0.0

# Production Optimization
whitenoise==6.6.0
buildCommand: pip install -r backend/requirements.txt
opencv-python-headless==4.9.0.80  # Headless version (no GUI dependencies)
numpy==1.26.4  # Required for OpenCV

buildCommand: |
  pip install --upgrade pip
  pip install --no-deps opencv-python-headless==4.9.0.80
  pip install -r backend/requirements.txt
